#:schema node_modules/wrangler/config-schema.json
name = "launchtube"
main = "dist/index.js"
compatibility_date = "2024-05-12"
workers_dev = true
minify = true

[[durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["CreditsDurableObject", "SequencerDurableObject"]

[[kv_namespaces]]
binding = "SUDOS"
id = "648ee8e36d1d48eaa2708465e2f76852"

[[d1_databases]]
binding = "DATABASE"
database_name = "obsrvr-launchtube-testnet"
database_id = "2cd89d5b-33a6-483d-80f5-65dfc31168ab"

[build]
command = "npm run build"

[define]
global = "globalThis"

[vars]
ENV = "development"
NATIVE_CONTRACT_ID="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"
RPC_URL="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
